apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Replace with your namespace
  name: pvc-scaler-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

