apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-scaler-rolebinding
  namespace: default  # Replace with your namespace
subjects:
- kind: ServiceAccount
  name: pvc-scaler-service-account
  namespace: default  # Replace with your namespace
roleRef:
  kind: Role
  name: pvc-scaler-role
  apiGroup: rbac.authorization.k8s.io

