apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-scaler-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-scaler-controller
  template:
    metadata:
      labels:
        app: pvc-scaler-controller
    spec:
      serviceAccountName: pvc-scaler-controller
      containers:
      - name: pvc-scaler
        image: pvc-controller:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBECONFIG
          value: "/etc/kubeconfig/kubeconfig"
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
          name: pvc-scaler-token
          readOnly: true
      volumes:
      - name: kubeconfig
        configMap:
          name: kubeconfig
      - name: pvc-scaler-token
        secret:
            secretName: pvc-scaler-token

